version: '3.8'

services:
  vista_redis_stack:
    image: redis/redis-stack:latest
    container_name: vista_redis_stack
    ports:
      - "8003:8001"
      - "6380:6379"
    volumes:
      - vista-redis-volume

volumes:
  vista-redis-volume:
    external: true