version: '3.9'

services:
  vista_mongo:
    container_name: vista_mongo
    restart: on-failure
    dns:
      - 178.22.122.100
      - 185.51.200.2
    image: mongo:latest
    volumes:
      - vista-mongo-volume

  app:
    container_name: app
    image: node:20
    command: 'nodemon'
    depends_on:
      - vista_mongo

volumes:
  vista-mongo-volume:
    external: true